sudo: required
services:
  - docker

before_install:
  - docker build -t darglk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run darglk/react-test npm test -- --coverage

after_success:
  - docker build -t darglk/multi-client ./client
  - docker build -t darglk/multi-nginx ./nginx
  - docker build -t darglk/multi-server ./server
  - docker build -t darglk/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push darglk/multi-client
  - docker push darglk/multi-nginx
  - docker push darglk/multi-server
  - docker push darglk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-407417679369
  bucket_path: docker-multi
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY